---

- name: Install PHP
  yum:
    name: ['php','php-mysql']
    state: present

- name: Restart Apache
  service:
    name: httpd
    state: restarted

- name: creating a template for remote
  copy:
    src: info.php
    dest: /var/www/html/info.php
...
